### ISSUE TITLE
No permission to write on folder

### ISSUE THREAD

**Issue by juliohm** [SebastianM-C/PkgCite.jl#25]
Trying to run the `get_tool_citation()` command from the default folder that the REPL starts leads to an error because the package can't read/write to `C::\\Windows\\System32`. You should probably use a temporary file to build the bib? Base has utility functions to write temporary files that are OS-agnostic.

**Comment by SebastianM-C** [comment]
The package assumes that you use the functions from an environment, since there's no API in the package manager to get the dependencies from an arbitrary folder.

What I could do is to have a better error when the current folder is not writable. I'm not sure if using a temporary file would help, since it might be harder for users to discover the file, and if I'll then copy / move it to the current directory, we're back at square one.

The user can provide an arbitrary path as the filename (https://sebastianm-c.github.io/PkgCite.jl/dev/#PkgCite.get_citations).

**Comment by juliohm** [comment]
I think you should always use a temp file and then show the path to the end user. Alternatively you could ask if the end user wants to copy the file to somewhere else. That way  you can be sure that no errors will occur.

**Comment by juliohm** [comment]
In other words, the algorithm could work as follows:

1. create temp file and write to it
2. try to save in current folder
3. in case of success, print path
4. otherwise prompt user to ask where to save
